// 装備マスタ 16種 = 武器10 / 防具3 / アクセサリ3（docs/18_Skill_Design.md §6.2〜§6.3 完全転記）
// isStarter: availability = both / starter_unlock → true、run_drop → false
// base_statsの hp は schema.prisma / types.ts に合わせ maxHp として保持
import type { EquipmentMaster } from './types';

export const EQUIPMENT: EquipmentMaster[] = [
  // ---- 武器 10種（docs/18 §6.2） ----
  {
    code: 'iron_sword',
    name: '鉄の剣',
    description: '使い込まれた無骨な鉄剣。最初の相棒。',
    slot: 'weapon',
    weaponType: 'sword',
    rarity: 'common',
    baseStats: { atk: 3 },
    passiveEffect: null,
    basePrice: 50,
    isStarter: true, // both（初期解放済）
    sortOrder: 1,
  },
  {
    code: 'knight_blade',
    name: '騎士の剣',
    description: '遺跡に眠っていた騎士団の制式剣。攻守に優れる。',
    slot: 'weapon',
    weaponType: 'sword',
    rarity: 'rare',
    baseStats: { atk: 6, def: 1 },
    passiveEffect: null,
    basePrice: 100,
    isStarter: false,
    sortOrder: 2,
  },
  {
    code: 'flame_brand',
    name: '焔の大剣',
    description: '刀身が絶えず燃え続ける大剣。攻撃時に火傷を負わせることがある。',
    slot: 'weapon',
    weaponType: 'sword',
    rarity: 'epic',
    baseStats: { atk: 8 },
    passiveEffect: [
      { effectType: 'status', params: { status: 'burn', chancePct: 20 }, trigger: 'on_attack' },
    ],
    basePrice: 200,
    isStarter: false,
    sortOrder: 3,
  },
  {
    code: 'oak_rod',
    name: '樫の杖',
    description: '樫の木から削り出した素朴な杖。手に馴染む。',
    slot: 'weapon',
    weaponType: 'rod',
    rarity: 'common',
    baseStats: { atk: 2, maxHp: 5 },
    passiveEffect: null,
    basePrice: 45,
    isStarter: true, // both（リリア解放時に付与）
    sortOrder: 4,
  },
  {
    code: 'tide_staff',
    name: '潮流の杖',
    description: '潮の満ち引きを宿す杖。水属性の術を増幅する。',
    slot: 'weapon',
    weaponType: 'rod',
    rarity: 'rare',
    baseStats: { atk: 5 },
    passiveEffect: [
      {
        effectType: 'stat_passive',
        params: { stats: { dmgDealtPct: 10 } },
        trigger: 'always',
        elementCondition: 'water', // 水属性与ダメのみ+10%（docs/18 ISSUE-185）
      },
    ],
    basePrice: 100,
    isStarter: false,
    sortOrder: 5,
  },
  {
    code: 'sage_staff',
    name: '賢者の杖',
    description: '古の賢者が残した杖。持つ者の魔力を循環させる。',
    slot: 'weapon',
    weaponType: 'rod',
    rarity: 'epic',
    baseStats: { atk: 7 },
    passiveEffect: [
      { effectType: 'stat_passive', params: { stats: { spRegen: 1 } }, trigger: 'always' },
    ],
    basePrice: 210,
    isStarter: false,
    sortOrder: 6,
  },
  {
    code: 'bronze_dagger',
    name: '青銅の短剣',
    description: '軽くて扱いやすい青銅の短剣。',
    slot: 'weapon',
    weaponType: 'dagger',
    rarity: 'common',
    baseStats: { atk: 2, spd: 1 },
    passiveEffect: null,
    basePrice: 45,
    isStarter: true, // both（ガルド解放時に付与）
    sortOrder: 7,
  },
  {
    code: 'gale_dagger',
    name: '疾風の短剣',
    description: '風の加護を受けた短剣。急所を捉えやすい。',
    slot: 'weapon',
    weaponType: 'dagger',
    rarity: 'rare',
    baseStats: { atk: 4, spd: 2 },
    passiveEffect: [
      { effectType: 'stat_passive', params: { stats: { critRate: 5 } }, trigger: 'always' },
    ],
    basePrice: 105,
    isStarter: false,
    sortOrder: 8,
  },
  {
    code: 'viper_fang',
    name: '毒蛇の牙',
    description: '毒蛇の牙から作られた短剣。攻撃時に毒を流し込むことがある。',
    slot: 'weapon',
    weaponType: 'dagger',
    rarity: 'epic',
    baseStats: { atk: 5, spd: 1 },
    passiveEffect: [
      { effectType: 'status', params: { status: 'poison', chancePct: 30 }, trigger: 'on_attack' },
    ],
    basePrice: 200,
    isStarter: false,
    sortOrder: 9,
  },
  {
    code: 'warhammer',
    name: 'ウォーハンマー',
    description: '重量級の戦鎚。振りは遅いが一撃は重い。',
    slot: 'weapon',
    weaponType: 'hammer',
    rarity: 'rare',
    baseStats: { atk: 7, spd: -1 },
    passiveEffect: null,
    basePrice: 95,
    isStarter: false,
    sortOrder: 10,
  },
  // ---- 防具 3種（docs/18 §6.3） ----
  {
    code: 'leather_armor',
    name: '革の鎧',
    description: 'なめし革の軽鎧。動きを妨げない。',
    slot: 'armor',
    weaponType: null,
    rarity: 'common',
    baseStats: { def: 3, maxHp: 5 },
    passiveEffect: null,
    basePrice: 50,
    isStarter: true, // both（初期解放済）
    sortOrder: 11,
  },
  {
    code: 'chain_mail',
    name: '鎖帷子',
    description: '細かな鎖を編んだ鎧。斬撃に強い。',
    slot: 'armor',
    weaponType: null,
    rarity: 'rare',
    baseStats: { def: 6, maxHp: 10 },
    passiveEffect: null,
    basePrice: 110,
    isStarter: false,
    sortOrder: 12,
  },
  {
    code: 'guardian_plate',
    name: '守護者の鎧',
    description: '遺跡の守護者を模した重鎧。戦闘開始時に加護の障壁を張る。',
    slot: 'armor',
    weaponType: null,
    rarity: 'epic',
    baseStats: { def: 9, maxHp: 20, spd: -1 },
    passiveEffect: [
      {
        effectType: 'shield',
        params: { hpPctOfMax: 10, turns: null },
        trigger: 'battle_start',
      },
    ],
    basePrice: 220,
    isStarter: false,
    sortOrder: 13,
  },
  // ---- アクセサリ 3種（docs/18 §6.3） ----
  {
    code: 'power_ring',
    name: '力の指輪',
    description: '嵌めた者の膂力を高める指輪。',
    slot: 'accessory',
    weaponType: null,
    rarity: 'common',
    baseStats: { atk: 2 },
    passiveEffect: null,
    basePrice: 40,
    isStarter: true, // both（初期解放済）
    sortOrder: 14,
  },
  {
    code: 'swift_boots',
    name: '疾風のブーツ',
    description: '風のように軽い長靴。身のこなしが速くなる。',
    slot: 'accessory',
    weaponType: null,
    rarity: 'rare',
    baseStats: { spd: 3, eva: 3 },
    passiveEffect: null,
    basePrice: 100,
    isStarter: false,
    sortOrder: 15,
  },
  {
    code: 'hawk_amulet',
    name: '鷹の護符',
    description: '鷹の目を封じた護符。急所を穿つ力を授ける。',
    slot: 'accessory',
    weaponType: null,
    rarity: 'epic',
    baseStats: { critRate: 10, critDmg: 20 },
    passiveEffect: null,
    basePrice: 210,
    isStarter: false,
    sortOrder: 16,
  },
];

// --- docs間の差異と採用判断 ---
// - docs/18 §6.2/6.3の base_stats「hp」は schema.prisma / types.ts の `maxHp` キーへ正規化
// - availability（both / starter_unlock / run_drop）は schema.prisma の isStarter booleanへ正規化
//   （both・starter_unlock → true / run_drop → false）
