// スキルマスタ 20種（docs/18_Skill_Design.md §3.1 完全転記）
// 構成: キャラ初期スキル3種（#1〜3）+ 固有スキル3種（#4〜6）+ 汎用14種（#7〜20）
// params は Lv1 時点の値。レベル差分は levelScaling.byLevel（docs/18 §2.5）
import type { SkillMaster } from './types';

export const SKILLS: SkillMaster[] = [
  // ---- キャラ初期スキル（#1〜3。該当キャラ専用・ラン開始時所持・8枠内） ----
  {
    code: 'skill_flame_slash',
    name: '火炎斬り',
    description: '炎を纏った斬撃で敵単体に火属性ダメージを与える。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'fire',
    maxLevel: 3,
    characterCode: 'swordsman_rain',
    isInnate: false,
    sortOrder: 1,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.6 },
        levelScaling: { byLevel: { '2': { mult: 1.8 }, '3': { mult: 2.0 } } },
      },
    ],
  },
  {
    code: 'skill_aqua_bolt',
    name: 'アクアボルト',
    description: '水の魔弾を放ち、敵単体に水属性ダメージを与える。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'water',
    maxLevel: 3,
    characterCode: 'mage_lilia',
    isInnate: false,
    sortOrder: 2,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.7 },
        levelScaling: { byLevel: { '2': { mult: 1.9 }, '3': { mult: 2.2 } } },
      },
    ],
  },
  {
    code: 'skill_gale_slash',
    name: '疾風の刃',
    description: '風を纏う高速の刃。クリティカルが出やすい風属性攻撃。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'wind',
    maxLevel: 3,
    characterCode: 'rogue_gald',
    isInnate: false,
    sortOrder: 3,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.3, addCritRate: 15 },
        levelScaling: {
          byLevel: {
            '2': { mult: 1.5, addCritRate: 20 },
            '3': { mult: 1.7, addCritRate: 25 },
          },
        },
      },
    ],
  },
  // ---- 固有スキル（#4〜6。is_innate=true・8枠の枠外・強化不可） ----
  {
    code: 'skill_indomitable',
    name: '不屈',
    description: 'ラン中1回、致死ダメージを受けてもHP1で耐える。',
    skillType: 'passive',
    rarity: 'epic',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 1,
    characterCode: 'swordsman_rain',
    isInnate: true,
    sortOrder: 4,
    effects: [
      {
        order: 1,
        effectType: 'revive_guard',
        params: { oncePerRun: true, surviveHp: 1 },
      },
    ],
  },
  {
    code: 'skill_mana_cycle',
    name: '魔力循環',
    description: '独自の呼吸法により毎ターンのSP回復量が+1される。',
    skillType: 'passive',
    rarity: 'epic',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 1,
    characterCode: 'mage_lilia',
    isInnate: true,
    sortOrder: 5,
    effects: [
      {
        order: 1,
        effectType: 'stat_passive',
        params: { stats: { spRegen: 1 } },
      },
    ],
  },
  {
    code: 'skill_first_strike',
    name: '先手必勝',
    description: '戦闘1ターン目に与えるダメージが+30%される。',
    skillType: 'passive',
    rarity: 'epic',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 1,
    characterCode: 'rogue_gald',
    isInnate: true,
    sortOrder: 6,
    effects: [
      {
        order: 1,
        effectType: 'stat_passive',
        params: { stats: { dmgDealtPct: 30 }, condition: { turnEq: 1 } },
      },
    ],
  },
  // ---- 汎用スキル（#7〜20。全キャラ取得可） ----
  {
    code: 'skill_power_strike',
    name: '強撃',
    description: '力を込めた一撃で敵単体にダメージを与える。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 7,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.5 },
        levelScaling: { byLevel: { '2': { mult: 1.7 }, '3': { mult: 1.9 } } },
      },
    ],
  },
  {
    code: 'skill_poison_stab',
    name: '毒針',
    description: '毒を塗った針で突き、高確率で毒を付与する。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 8,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.0 },
        levelScaling: { byLevel: { '2': { mult: 1.1 }, '3': { mult: 1.2 } } },
      },
      {
        order: 2,
        effectType: 'status',
        params: { status: 'poison', chancePct: 80, turns: 3 },
        levelScaling: { byLevel: { '2': { chancePct: 90 }, '3': { chancePct: 100 } } },
      },
    ],
  },
  {
    code: 'skill_venom_burst',
    name: 'ベノムバースト',
    description: '敵単体を攻撃。毒状態の敵には倍率が上昇する。',
    skillType: 'active',
    rarity: 'rare',
    spCost: 4,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 9,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.3, bonusVsStatus: { status: 'poison', mult: 1.8 } },
        levelScaling: {
          byLevel: {
            '2': { mult: 1.5, bonusVsStatus: { status: 'poison', mult: 2.1 } },
            '3': { mult: 1.7, bonusVsStatus: { status: 'poison', mult: 2.4 } },
          },
        },
      },
    ],
  },
  {
    code: 'skill_toxic_cloud',
    name: '毒霧',
    description: '毒の霧を撒き、敵全体にダメージと毒を与える。',
    skillType: 'active',
    rarity: 'epic',
    spCost: 7,
    targetType: 'enemy_all',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 10,
    effects: [
      {
        order: 1,
        effectType: 'damage_aoe',
        params: { mult: 0.9 },
        levelScaling: { byLevel: { '2': { mult: 1.0 }, '3': { mult: 1.2 } } },
      },
      {
        order: 2,
        effectType: 'status',
        params: { status: 'poison', chancePct: 70, turns: 3 },
        levelScaling: { byLevel: { '2': { chancePct: 80 }, '3': { chancePct: 90 } } },
      },
    ],
  },
  {
    code: 'skill_first_aid',
    name: '応急手当',
    description: 'HPを回復する。Lv3では状態異常も1つ解除する。',
    skillType: 'active',
    rarity: 'common',
    spCost: 4,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 11,
    effects: [
      {
        order: 1,
        effectType: 'heal',
        params: { hpPctOfMax: 25 },
        levelScaling: { byLevel: { '2': { hpPctOfMax: 30 }, '3': { hpPctOfMax: 35 } } },
      },
      {
        order: 2,
        effectType: 'cleanse',
        params: { count: 1 },
        levelScaling: { unlockAtLevel: 3 },
      },
    ],
  },
  {
    code: 'skill_war_cry',
    name: '雄叫び',
    description: '雄叫びを上げ、自身の攻撃力を3ターン上昇させる。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 12,
    effects: [
      {
        order: 1,
        effectType: 'buff',
        params: { buff: 'atkUp', valuePct: 20, turns: 3 },
        levelScaling: { byLevel: { '2': { valuePct: 25 }, '3': { valuePct: 30 } } },
      },
    ],
  },
  {
    code: 'skill_stone_skin',
    name: 'ストーンスキン',
    description: '肌を石化させ、被ダメージを吸収するシールドを張る。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 13,
    effects: [
      {
        order: 1,
        effectType: 'shield',
        params: { hpPctOfMax: 20, turns: null },
        levelScaling: { byLevel: { '2': { hpPctOfMax: 25 }, '3': { hpPctOfMax: 30 } } },
      },
    ],
  },
  {
    code: 'skill_counter_stance',
    name: '反撃の構え',
    description: '防御コマンド選択中に被弾すると反撃する。',
    skillType: 'passive',
    rarity: 'rare',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 14,
    effects: [
      {
        order: 1,
        effectType: 'counter',
        params: { mult: 0.6, onlyWhenDefending: true, chancePct: 100 },
        levelScaling: { byLevel: { '2': { mult: 0.8 }, '3': { mult: 1.0 } } },
      },
    ],
  },
  {
    code: 'skill_keen_eyes',
    name: '鷹の目',
    description: '常時クリティカル率が上昇する。',
    skillType: 'passive',
    rarity: 'common',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 15,
    effects: [
      {
        order: 1,
        effectType: 'stat_passive',
        params: { stats: { critRate: 8 } },
        levelScaling: {
          byLevel: { '2': { stats: { critRate: 11 } }, '3': { stats: { critRate: 14 } } },
        },
      },
    ],
  },
  {
    code: 'skill_deadly_focus',
    name: '死点撃ち',
    description: '急所を見極め、2ターンの間クリティカル率が大きく上昇する。',
    skillType: 'active',
    rarity: 'rare',
    spCost: 4,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 16,
    effects: [
      {
        order: 1,
        effectType: 'buff',
        params: { buff: 'critUp', valuePct: 25, turns: 2 },
        levelScaling: { byLevel: { '2': { valuePct: 30 }, '3': { valuePct: 35 } } },
      },
    ],
  },
  {
    code: 'skill_assassinate',
    name: '暗殺剣',
    description: '必殺の一撃。高倍率かつクリティカルが出やすい。',
    skillType: 'active',
    rarity: 'epic',
    spCost: 8,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 17,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 2.6, addCritRate: 30 },
        levelScaling: { byLevel: { '2': { mult: 2.9 }, '3': { mult: 3.0 } } },
      },
    ],
  },
  {
    code: 'skill_blood_edge',
    name: '血吸いの刃',
    description: '敵単体を攻撃し、与ダメージの50%を自身のHPとして吸収する。',
    skillType: 'active',
    rarity: 'rare',
    spCost: 5,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 18,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 1.4 },
        levelScaling: { byLevel: { '2': { mult: 1.6 }, '3': { mult: 1.8 } } },
      },
      {
        // lifestealは直前damage行の与ダメを参照するためorder=2必須（docs/18 実装注意5）
        order: 2,
        effectType: 'lifesteal',
        params: { ratePct: 50 },
      },
    ],
  },
  {
    code: 'skill_meditate',
    name: '瞑想',
    description: '精神を集中し、SPを即座に回復する。',
    skillType: 'active',
    rarity: 'common',
    spCost: 0,
    targetType: 'self',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 19,
    effects: [
      {
        order: 1,
        effectType: 'sp_gain',
        params: { amount: 4 },
        levelScaling: { byLevel: { '2': { amount: 5 }, '3': { amount: 6 } } },
      },
    ],
  },
  {
    code: 'skill_armor_break',
    name: '鎧砕き',
    description: '敵の鎧を砕き、防御力を3ターン低下させる。',
    skillType: 'active',
    rarity: 'common',
    spCost: 3,
    targetType: 'enemy_single',
    element: 'none',
    maxLevel: 3,
    characterCode: null,
    isInnate: false,
    sortOrder: 20,
    effects: [
      {
        order: 1,
        effectType: 'damage',
        params: { mult: 0.8 },
      },
      {
        order: 2,
        effectType: 'debuff',
        params: { debuff: 'defDown', valuePct: 25, turns: 3 },
        levelScaling: { byLevel: { '2': { valuePct: 30 }, '3': { valuePct: 35 } } },
      },
    ],
  },
];

// --- docs間の差異と採用判断（優先順: 19 > 18 > 17 > 05） ---
// - 初期スキル倍率: docs/05はflame_slash 1.5 / aqua_bolt 1.6を記載（仮決定注記あり）→ docs/18の1.6 / 1.7を採用
// - ガルド初期スキル: docs/05は skill_gale_edge（mult1.4 / SP2）→ docs/18の skill_gale_slash（mult1.3+addCrit15 / SP3）を採用
// - skill_type: docs/18 §3.1のUI分類（heal/buff/debuff等）はDB CHECK制約（active/passive）に従い
//   SP消費スキルを全てactiveへ正規化（types.tsコメント / DEC-240準拠）
