// 永続強化ツリー 12ノード（docs/05_Game_Design.md §4.2 完全転記。総コスト3,780シャード）
// 各段階を独立ノード（maxRank=1）とし、prerequisiteCodeで前提を表現する
import type { UpgradeNodeMaster } from './types';

export const UPGRADE_NODES: UpgradeNodeMaster[] = [
  {
    code: 'upg_hp_1',
    name: '生命の刻印I',
    description: '全キャラの初期maxHpが+5%される。',
    effect: { type: 'startHpPct', valuePerRank: 5 },
    maxRank: 1,
    costPerRank: [100],
    prerequisiteCode: null,
    sortOrder: 1,
  },
  {
    code: 'upg_hp_2',
    name: '生命の刻印II',
    description: '全キャラの初期maxHpがさらに+5%される（累計+10%）。',
    effect: { type: 'startHpPct', valuePerRank: 5 },
    maxRank: 1,
    costPerRank: [250],
    prerequisiteCode: 'upg_hp_1',
    sortOrder: 2,
  },
  {
    code: 'upg_hp_3',
    name: '生命の刻印III',
    description: '全キャラの初期maxHpがさらに+5%される（累計+15%）。',
    effect: { type: 'startHpPct', valuePerRank: 5 },
    maxRank: 1,
    costPerRank: [500],
    prerequisiteCode: 'upg_hp_2',
    sortOrder: 3,
  },
  {
    code: 'upg_atk_1',
    name: '剛力の刻印I',
    description: '全キャラの初期atkが+3%される。',
    effect: { type: 'startAtkPct', valuePerRank: 3 },
    maxRank: 1,
    costPerRank: [100],
    prerequisiteCode: null,
    sortOrder: 4,
  },
  {
    code: 'upg_atk_2',
    name: '剛力の刻印II',
    description: '全キャラの初期atkがさらに+3%される（累計+6%）。',
    effect: { type: 'startAtkPct', valuePerRank: 3 },
    maxRank: 1,
    costPerRank: [250],
    prerequisiteCode: 'upg_atk_1',
    sortOrder: 5,
  },
  {
    code: 'upg_atk_3',
    name: '剛力の刻印III',
    description: '全キャラの初期atkがさらに+3%される（累計+9%）。',
    effect: { type: 'startAtkPct', valuePerRank: 3 },
    maxRank: 1,
    costPerRank: [500],
    prerequisiteCode: 'upg_atk_2',
    sortOrder: 6,
  },
  {
    code: 'upg_gold_1',
    name: '探索者の路銀I',
    description: 'ラン開始時の所持ゴールドが+50される。',
    effect: { type: 'startGold', valuePerRank: 50 },
    maxRank: 1,
    costPerRank: [80],
    prerequisiteCode: null,
    sortOrder: 7,
  },
  {
    code: 'upg_gold_2',
    name: '探索者の路銀II',
    description: 'ラン開始時の所持ゴールドがさらに+50される（累計+100）。',
    effect: { type: 'startGold', valuePerRank: 50 },
    maxRank: 1,
    costPerRank: [200],
    prerequisiteCode: 'upg_gold_1',
    sortOrder: 8,
  },
  {
    code: 'upg_reroll_1',
    name: '選択の余地',
    description: 'スキル3択のリロール回数が+1回/ランされる（計2回）。',
    effect: { type: 'rerollPlus', valuePerRank: 1 },
    maxRank: 1,
    costPerRank: [300],
    prerequisiteCode: 'upg_gold_1',
    sortOrder: 9,
  },
  {
    code: 'upg_relic_1',
    name: '冒険の御守り',
    description: 'ラン開始時にcommonレリック1個をランダムに所持して出発する。',
    effect: { type: 'startRelic', valuePerRank: 1 },
    maxRank: 1,
    costPerRank: [600],
    prerequisiteCode: 'upg_gold_2',
    sortOrder: 10,
  },
  {
    code: 'upg_shard_1',
    name: '魂の共鳴I',
    description: 'ソウルシャード獲得量が+10%される。',
    effect: { type: 'shardGainPct', valuePerRank: 10 },
    maxRank: 1,
    costPerRank: [300],
    prerequisiteCode: null,
    sortOrder: 11,
  },
  {
    code: 'upg_shard_2',
    name: '魂の共鳴II',
    description: 'ソウルシャード獲得量がさらに+10%される（累計+20%、加算）。',
    effect: { type: 'shardGainPct', valuePerRank: 10 },
    maxRank: 1,
    costPerRank: [600],
    prerequisiteCode: 'upg_shard_1',
    sortOrder: 12,
  },
];
